# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0003_auto_20160523_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecoassinatura',
            name='CEP',
            field=models.CharField(max_length=9),
        ),
    ]
