# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0004_auto_20160523_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='sistOp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Assinante.sistOp'),
            preserve_default=False,
        ),
    ]
