# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0005_auto_20160524_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistop',
            name='sistOp',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
