# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0008_auto_20160524_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinante',
            name='CPF',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
    ]
