# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0021_auto_20160525_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinante',
            name='dAssinatura',
        ),
        migrations.RemoveField(
            model_name='assinante',
            name='dBanco',
        ),
        migrations.RemoveField(
            model_name='assinante',
            name='endAssinatura',
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='assinatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Assinante.Assinante'),
        ),
        migrations.RemoveField(
            model_name='dadosassinatura',
            name='generosPessoais',
        ),
        migrations.AddField(
            model_name='dadosassinatura',
            name='generosPessoais',
            field=models.ManyToManyField(to='Assinante.Genero'),
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='assinatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Assinante.Assinante'),
        ),
        migrations.AlterField(
            model_name='enderecoassinatura',
            name='assinatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Assinante.Assinante'),
        ),
    ]
