# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0022_auto_20160525_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoJogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.Assinante')),
            ],
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
    ]
