# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0026_auto_20160525_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='chaveDownload',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Assinante.ChaveDownload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='jogosPedidos',
            field=models.ManyToManyField(to='Assinante.Jogo'),
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
    ]
