# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0027_auto_20160525_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicojogos',
            name='listaPedidos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Assinante.Pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
    ]
