# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0039_auto_20160527_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinante',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
        migrations.DeleteModel(
            name='Assinante',
        ),
    ]
