# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0041_auto_20160527_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='chaveDownload',
        ),
        migrations.AddField(
            model_name='chavedownload',
            name='jogo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Assinante.Jogo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chavedownload',
            name='pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Assinante.Pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo',
            name='nomeImagem',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='codigoSeguranca',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipoMidia',
            field=models.CharField(choices=[('FISICA', 'Fisica'), ('DIGITAL', 'Digital')], default='DIGITAL', max_length=10),
        ),
    ]
