# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0042_auto_20160604_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='tipoMidia',
            field=models.CharField(choices=[('FISICA', 'Fisica'), ('DIGITAL', 'Digital')], default='DIGITAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
    ]
