# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0044_auto_20160604_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
        migrations.AlterField(
            model_name='enderecoassinatura',
            name='numeroRua',
            field=models.IntegerField(default=0),
        ),
    ]
