# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0047_auto_20160604_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicojogos',
            name='listaPedidos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='assinatura',
        ),
        migrations.AddField(
            model_name='pedido',
            name='historico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Assinante.HistoricoJogos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
    ]
