# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0048_auto_20160604_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosassinatura',
            name='memRAM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='memVideo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='precoPorJogo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='processador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Assinante.Processadores'),
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
    ]
