# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assinante', '0052_auto_20160604_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='nomeImagem',
        ),
        migrations.AddField(
            model_name='jogo',
            name='img1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo',
            name='img2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosassinatura',
            name='sistOp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Assinante.SistOp'),
        ),
    ]
