# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='ident',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
