# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acervo', '0002_jogo_ident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='listaGeneros',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
    ]
